site_name: My Docs

theme:
  name: 'material'
  
nav:
  - Getting Started: "index.md"
  - Technologies & Setup: "technologies-setup.md"
  - Architecture: "architecture.md"
  - Deployment: "deployment.md"
  - Contributing: "contributing.md"
  - Terraform Modules : "teraform-module.md"
