name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger this action when changes are pushed to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project Y Repository
      uses: actions/checkout@v2
      with:
        repository: vishnumhetre/test-project-y

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install MkDocs and MkDocs Material
      run: |
        pip install mkdocs
        pip install mkdocs-material

    - name: Build Documentation
      run: mkdocs build

    - name: Deploy to GitHub Pages (optional)
      run: mkdocs gh-deploy --force